#!/usr/bin/env python
# -*- coding: utf-8 -*-

LANGUAGES = {
    'Arabic':'ar',
    'Bengali':'bn',
    'Czech':'cs',
    'Welsh':'cy', 
    'Danish':'da', 
    'German':'de', 
    'Greek':'el', 
    'English':'en', 
    'Español':'es', 
    'Argentinean Spanish':'es_AR',
    'French':'fr', 
    'Galician':'gl', 
    'Hungarian':'hu', 
    'Hebrew':'he', 
    'Icelandic':'is', 
    'Italian':'it', 
    'Japanese':'ja', 
    'Dutch':'nl', 
    'Norwegian':'no', 
    'Brazilian':'pt-br', 
    'Romanian':'ro', 
    'Russian':'ru', 
    'Slovak':'sk', 
    'Slovenian':'sl', 
    'Serbian':'sr', 
    'Swedish':'sv', 
    'Tamil':'ta', 
    'Ukrainian':'uk', 
    'Simplified Chinese':'zh-cn', 
    'Traditional Chinese':'zh-tw', 
    }
